netbox_mikrotik/urls.py
from django.urls import include, path
from utilities.urls import get_model_urls

from netbox_mikrotik.views import *  # noqa: F401

app_name = "netbox_mikrotik"

urlpatterns = [path("dhcp-servers/",
                    include(get_model_urls(app_name, "mikrotikdhcpserver", detail=False))),
               path("dhcp-servers/<int:pk>/",
                    include(get_model_urls(app_name, "mikrotikdhcpserver"))),
               path("dhcp-leases/",
                    include(get_model_urls(app_name, "mikrotikdhcplease", detail=False))),
               path("dhcp-leases/<int:pk>/",
                    include(get_model_urls(app_name, "mikrotikdhcplease"))),
               path("devices/",
                    include(get_model_urls(app_name, "mikrotikdevice", detail=False))),
               path("devices/<int:pk>/",
                    include(get_model_urls(app_name, "mikrotikdevice")))]

netbox_mikrotik/models/dhcp.py
from django.db.models import CharField, ForeignKey, CASCADE
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from netbox.models import NetBoxModel

__all__ = ("MikrotikDhcpServer", "MikrotikDhcpLease")


class MikrotikDhcpServer(NetBoxModel):
    mikrotik_device = ForeignKey(
        verbose_name=_("Mikrotik Device"),
        to="netbox_mikrotik.MikrotikDevice",
        on_delete=CASCADE,
        related_name="mikrotik_dhcp_servers",
        null=False,
        blank=False
    )
    name = CharField(max_length=64, null=False, blank=False)

    class Meta:
        db_table = "netbox_mikrotik_dhcp_server"
        verbose_name = _("DHCP Server")
        verbose_name_plural = _("DHCP Servers")
        ordering = ["name"]

    def __str__(self):
        return self.name

    def validate_unique(self, *args, **kwargs):
        super().validate_unique(*args, **kwargs)
        if self.__class__.objects.filter(mikrotik_device=self.mikrotik_device,
                                         name=self.name).exists():
            raise ValidationError(
                message=f"{self.__class__.__name__} with this (mikrotik_device, name) already exists.",
                code="unique_together"
            )


class MikrotikDhcpLease(NetBoxModel):
    mikrotik_dhcp_server = ForeignKey(
        verbose_name=_("Mikrotik DHCP Server"),
        to="netbox_mikrotik.MikrotikDhcpServer",
        on_delete=CASCADE,
        related_name="netbox_mikrotik_dhcp_leases",
        null=False,
        blank=False
    )
    mac_address = ForeignKey(
        verbose_name=_("MAC Address"),
        to="dcim.MACAddress",
        on_delete=CASCADE,
        related_name="netbox_mikrotik_dhcp_leases",
        null=False,
        blank=False
    )

    class Meta:
        db_table = "netbox_mikrotik_dhcp_lease"
        verbose_name = _("DHCP Lease")
        verbose_name_plural = _("DHCP Leases")
        ordering = ["mac_address"]

    def __str__(self):
        return f"{self.mikrotik_dhcp_server.name} - {self.mac_address}"

netbox_mikrotik/views/device.py
from netbox.views.generic import ObjectListView, ObjectView, ObjectEditView, ObjectDeleteView, BulkImportView, \
    BulkEditView, BulkDeleteView
from utilities.views import register_model_view

from netbox_mikrotik.models import MikrotikDevice
from netbox_mikrotik.tables import MikrotikDeviceTable
from netbox_mikrotik.filtersets import MikrotikDeviceFilterSet
from netbox_mikrotik.forms import MikrotikDeviceForm

__all__ = ("MikrotikDeviceListView",
           "MikrotikDeviceView",
           "MikrotikDeviceEditView",
           "MikrotikDeviceDeleteView",
           "MikrotikDeviceBulkImportView",
           "MikrotikDeviceBulkEditView",
           "MikrotikDeviceBulkDeleteView")


@register_model_view(MikrotikDevice, "list", path="", detail=False)
class MikrotikDeviceListView(ObjectListView):
    queryset = MikrotikDevice.objects.all()
    filterset = MikrotikDeviceFilterSet
    # filterset_form = MikrotikDeviceForm ' ToDo
    table = MikrotikDeviceTable


@register_model_view(MikrotikDevice)
class MikrotikDeviceView(ObjectView):
    queryset = MikrotikDevice.objects.all()


@register_model_view(MikrotikDevice, "add", detail=False)
@register_model_view(MikrotikDevice, "edit")
class MikrotikDeviceEditView(ObjectEditView):
    queryset = MikrotikDevice.objects.all()
    form = MikrotikDeviceForm


@register_model_view(MikrotikDevice, "delete")
class MikrotikDeviceDeleteView(ObjectDeleteView):
    queryset = MikrotikDevice.objects.all()


@register_model_view(MikrotikDevice, "bulk_import", detail=False)
class MikrotikDeviceBulkImportView(BulkImportView):
    queryset = MikrotikDevice.objects.all()
    # model_form = ViewImportForm # ToDo
    table = MikrotikDeviceTable


@register_model_view(MikrotikDevice, "bulk_edit", path="edit", detail=False)
class MikrotikDeviceBulkEditView(BulkEditView):
    queryset = MikrotikDevice.objects.all()
    # filterset = ViewFilterSet # ToDo
    table = MikrotikDeviceTable
    # form = ViewBulkEditForm # ToDo


@register_model_view(MikrotikDevice, "bulk_delete", path="delete", detail=False)
class MikrotikDeviceBulkDeleteView(BulkDeleteView):
    queryset = MikrotikDevice.objects.all()
    # filterset = ViewFilterSet # ToDo
    table = MikrotikDeviceTable

netbox_mikrotik/templates/netbox_mikrotik/mikrotikdevice.html
{% extends 'generic/_base.html' %}
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load perms %}
{% load plugins %}
{% load tabs %}
{% load i18n %}

{% comment %}
Blocks:
  - page-header:          Content displayed above the primary page content
    - breadcrumbs:        Breadcrumb list items (HTML <li> elements)
    - object_identifier:  Unique identifier for the object
  - title:                Page title
  - subtitle:             Additional context displayed below the title
  - controls:             Control elements displayed between the header and content
    - control-buttons:    Action buttons (add/edit/delete/etc.)
      - extra_controls:   Any additional action buttons to display
  - tabs:                 Page tabs
  - content:              Primary page content
  - modals:               Any pre-loaded modals

Context:
  - object: The object being viewed
{% endcomment %}

{% block page-header %}
  <div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mt-2">

      {# Breadcrumbs #}
      <ol class="breadcrumb" aria-label="breadcrumbs">
        {% block breadcrumbs %}
          <li class="breadcrumb-item">
            <a href="{% url object|viewname:'list' %}">{{ object|meta:'verbose_name_plural'|bettertitle }}</a>
          </li>
        {% endblock breadcrumbs %}
      </ol>

      {# Object identifier #}
      <code class="d-block text-muted bg-transparent px-0">
        {% block object_identifier %}
          {{ object|meta:"app_label" }}.{{ object|meta:"model_name" }}:{{ object.pk }}
          {% if object.slug %}({{ object.slug }}){% endif %}
        {% endblock object_identifier %}
      </code>

    </div>
  </div>
  {{ block.super }}
{% endblock page-header %}

{% block title %}{{ object }}{% endblock %}

{% block subtitle %}
  <div class="text-secondary fs-5">
    {% trans "Created" %} {{ object.created|isodatetime:"minutes" }}
    {% if object.last_updated %}
      <span class="separator">&middot;</span>
      {% trans "Updated" %} {{ object.last_updated|isodatetime:"minutes" }}
    {% endif %}
  </div>
{% endblock subtitle %}

{% block controls %}
  <div class="btn-list justify-content-end mb-2">
    {% plugin_buttons object %}

    {# Add/edit/delete/etc. buttons #}
    {% block control-buttons %}

      {# Extra buttons #}
      {% block extra_controls %}{% endblock %}

      {# Default buttons #}
      {% if perms.extras.add_bookmark and object.bookmarks %}
        {% bookmark_button object %}
      {% endif %}
      {% if perms.extras.add_subscription and object.subscriptions %}
        {% subscribe_button object %}
      {% endif %}
      {% if request.user|can_add:object %}
        {% clone_button object %}
      {% endif %}
      {% if request.user|can_change:object %}
        {% edit_button object %}
      {% endif %}
      {% if request.user|can_delete:object %}
        {% delete_button object %}
      {% endif %}
    {% endblock control-buttons %}
  </div>

  {# Custom links #}
  <div class="d-flex justify-content-end">
    <div class="btn-list">
      {% block custom-links %}
        {% custom_links object %}
      {% endblock custom-links %}
    </div>
  </div>
{% endblock controls %}

{% block tabs %}
  <ul class="nav nav-tabs" role="presentation">
    {# Primary tab #}
    <li class="nav-item">
      <a class="nav-link{% if not tab %} active{% endif %}" href="{{ object.get_absolute_url }}">{{ object|meta:"verbose_name"|bettertitle }}</a>
    </li>

    {# Include tabs for registered model views #}
    {% model_view_tabs object %}
  </ul>
{% endblock tabs %}

{% block alerts %}
  {% plugin_alerts object %}
{% endblock alerts %}

{% block content %}
    <div class="row">
        <div class="col col-md-6">
            <div class="card">
                <h5 class="card-header">{% trans "Device" %}</h5>
                <table class="table table-hover attr-table">
                    <tr>
                        <th scope="row">{% trans "Device" %}</th>
                        <td>{{ object.device|linkify }}</td>
                    </tr>
                    {% if object.tenant %}
                        <tr>
                            <th scope="row">{% trans "Tenant" %}</th>
                            <td>
                                {% if object.tenant.group %}
                                    {{ object.tenant.group|linkify }} /
                                {% endif %}
                                {{ object.tenant|linkify|placeholder }}
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.ip_address %}
                        <tr>
                            <th scope="row">{% trans "IP Address" %}</th>
                            <td>
                                {{ object.ip_address|linkify }}
                            </td>
                        </tr>
                    {% endif %}
                    <tr>
                        <th scope="row">{% trans "Address List Synchronization" %}</th>
                        <td>{% checkmark object.address_list_sync %}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "DNS Synchronization" %}</th>
                        <td>{% checkmark object.dns_sync %}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "DHCP Synchronization" %}</th>
                        <td>{% checkmark object.dhcp_sync %}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Last Run" %}</th>
                        <td>{{ object.last_run }}</td>
                    </tr>
                </table>
            </div>
            {% include 'inc/panels/custom_fields.html' %}
        </div>
        <div class="col col-md-6">
            <div class="card">
                <h5 class="card-header">{% trans "Preview" %}</h5>
                <h5>ToDo</h5>
            </div>
        </div>
    </div>
{% endblock %}

{% block modals %}
  {% include 'inc/htmx_modal.html' %}
{% endblock modals %}

netbox_mikrotik/templates/netbox_mikrotik/mikrotikdhcplease.html
{% extends 'generic/_base.html' %}
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load perms %}
{% load plugins %}
{% load tabs %}
{% load i18n %}

{% comment %}
Blocks:
  - page-header:          Content displayed above the primary page content
    - breadcrumbs:        Breadcrumb list items (HTML <li> elements)
    - object_identifier:  Unique identifier for the object
  - title:                Page title
  - subtitle:             Additional context displayed below the title
  - controls:             Control elements displayed between the header and content
    - control-buttons:    Action buttons (add/edit/delete/etc.)
      - extra_controls:   Any additional action buttons to display
  - tabs:                 Page tabs
  - content:              Primary page content
  - modals:               Any pre-loaded modals

Context:
  - object: The object being viewed
{% endcomment %}

{% block page-header %}
  <div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mt-2">

      {# Breadcrumbs #}
      <ol class="breadcrumb" aria-label="breadcrumbs">
        {% block breadcrumbs %}
          <li class="breadcrumb-item">
            <a href="{% url object|viewname:'list' %}">{{ object|meta:'verbose_name_plural'|bettertitle }}</a>
          </li>
        {% endblock breadcrumbs %}
      </ol>

      {# Object identifier #}
      <code class="d-block text-muted bg-transparent px-0">
        {% block object_identifier %}
          {{ object|meta:"app_label" }}.{{ object|meta:"model_name" }}:{{ object.pk }}
          {% if object.slug %}({{ object.slug }}){% endif %}
        {% endblock object_identifier %}
      </code>

    </div>
  </div>
  {{ block.super }}
{% endblock page-header %}

{% block title %}{{ object }}{% endblock %}

{% block subtitle %}
  <div class="text-secondary fs-5">
    {% trans "Created" %} {{ object.created|isodatetime:"minutes" }}
    {% if object.last_updated %}
      <span class="separator">&middot;</span>
      {% trans "Updated" %} {{ object.last_updated|isodatetime:"minutes" }}
    {% endif %}
  </div>
{% endblock subtitle %}

{% block controls %}
  <div class="btn-list justify-content-end mb-2">
    {% plugin_buttons object %}

    {# Add/edit/delete/etc. buttons #}
    {% block control-buttons %}

      {# Extra buttons #}
      {% block extra_controls %}{% endblock %}

      {# Default buttons #}
      {% if perms.extras.add_bookmark and object.bookmarks %}
        {% bookmark_button object %}
      {% endif %}
      {% if perms.extras.add_subscription and object.subscriptions %}
        {% subscribe_button object %}
      {% endif %}
      {% if request.user|can_add:object %}
        {% clone_button object %}
      {% endif %}
      {% if request.user|can_change:object %}
        {% edit_button object %}
      {% endif %}
      {% if request.user|can_delete:object %}
        {% delete_button object %}
      {% endif %}
    {% endblock control-buttons %}
  </div>

  {# Custom links #}
  <div class="d-flex justify-content-end">
    <div class="btn-list">
      {% block custom-links %}
        {% custom_links object %}
      {% endblock custom-links %}
    </div>
  </div>
{% endblock controls %}

{% block tabs %}
  <ul class="nav nav-tabs" role="presentation">
    {# Primary tab #}
    <li class="nav-item">
      <a class="nav-link{% if not tab %} active{% endif %}" href="{{ object.get_absolute_url }}">{{ object|meta:"verbose_name"|bettertitle }}</a>
    </li>

    {# Include tabs for registered model views #}
    {% model_view_tabs object %}
  </ul>
{% endblock tabs %}

{% block alerts %}
  {% plugin_alerts object %}
{% endblock alerts %}

{% block content %}
    <div class="row">
        <div class="col col-md-12">
            <div class="card">
                <h5 class="card-header">{% trans "Device" %}</h5>
                <table class="table table-hover attr-table">
                    <tr>
                        <th scope="row">{% trans "Mikrotik DHCP Server" %}</th>
                        <td>{{ object.mikrotik_dhcp_server|linkify }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "MAC Address" %}</th>
                        <td>{{ object.mac_address|linkify }}</td>
                    </tr>
                </table>
            </div>
            {% include 'inc/panels/custom_fields.html' %}
        </div>
    </div>
{% endblock %}

{% block modals %}
  {% include 'inc/htmx_modal.html' %}
{% endblock modals %}

netbox_mikrotik/templates/netbox_mikrotik/mikrotikdhcpserver.html
{% extends 'generic/_base.html' %}
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load perms %}
{% load plugins %}
{% load tabs %}
{% load i18n %}

{% comment %}
Blocks:
  - page-header:          Content displayed above the primary page content
    - breadcrumbs:        Breadcrumb list items (HTML <li> elements)
    - object_identifier:  Unique identifier for the object
  - title:                Page title
  - subtitle:             Additional context displayed below the title
  - controls:             Control elements displayed between the header and content
    - control-buttons:    Action buttons (add/edit/delete/etc.)
      - extra_controls:   Any additional action buttons to display
  - tabs:                 Page tabs
  - content:              Primary page content
  - modals:               Any pre-loaded modals

Context:
  - object: The object being viewed
{% endcomment %}

{% block page-header %}
  <div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mt-2">

      {# Breadcrumbs #}
      <ol class="breadcrumb" aria-label="breadcrumbs">
        {% block breadcrumbs %}
          <li class="breadcrumb-item">
            <a href="{% url object|viewname:'list' %}">{{ object|meta:'verbose_name_plural'|bettertitle }}</a>
          </li>
        {% endblock breadcrumbs %}
      </ol>

      {# Object identifier #}
      <code class="d-block text-muted bg-transparent px-0">
        {% block object_identifier %}
          {{ object|meta:"app_label" }}.{{ object|meta:"model_name" }}:{{ object.pk }}
          {% if object.slug %}({{ object.slug }}){% endif %}
        {% endblock object_identifier %}
      </code>

    </div>
  </div>
  {{ block.super }}
{% endblock page-header %}

{% block title %}{{ object }}{% endblock %}

{% block subtitle %}
  <div class="text-secondary fs-5">
    {% trans "Created" %} {{ object.created|isodatetime:"minutes" }}
    {% if object.last_updated %}
      <span class="separator">&middot;</span>
      {% trans "Updated" %} {{ object.last_updated|isodatetime:"minutes" }}
    {% endif %}
  </div>
{% endblock subtitle %}

{% block controls %}
  <div class="btn-list justify-content-end mb-2">
    {% plugin_buttons object %}

    {# Add/edit/delete/etc. buttons #}
    {% block control-buttons %}

      {# Extra buttons #}
      {% block extra_controls %}{% endblock %}

      {# Default buttons #}
      {% if perms.extras.add_bookmark and object.bookmarks %}
        {% bookmark_button object %}
      {% endif %}
      {% if perms.extras.add_subscription and object.subscriptions %}
        {% subscribe_button object %}
      {% endif %}
      {% if request.user|can_add:object %}
        {% clone_button object %}
      {% endif %}
      {% if request.user|can_change:object %}
        {% edit_button object %}
      {% endif %}
      {% if request.user|can_delete:object %}
        {% delete_button object %}
      {% endif %}
    {% endblock control-buttons %}
  </div>

  {# Custom links #}
  <div class="d-flex justify-content-end">
    <div class="btn-list">
      {% block custom-links %}
        {% custom_links object %}
      {% endblock custom-links %}
    </div>
  </div>
{% endblock controls %}

{% block tabs %}
  <ul class="nav nav-tabs" role="presentation">
    {# Primary tab #}
    <li class="nav-item">
      <a class="nav-link{% if not tab %} active{% endif %}" href="{{ object.get_absolute_url }}">{{ object|meta:"verbose_name"|bettertitle }}</a>
    </li>

    {# Include tabs for registered model views #}
    {% model_view_tabs object %}
  </ul>
{% endblock tabs %}

{% block alerts %}
  {% plugin_alerts object %}
{% endblock alerts %}

{% block content %}
    <div class="row">
        <div class="col col-md-12">
            <div class="card">
                <h5 class="card-header">{% trans "Device" %}</h5>
                <table class="table table-hover attr-table">
                    <tr>
                        <th scope="row">{% trans "Mikrotik Device" %}</th>
                        <td>{{ object.mikrotik_device|linkify }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% trans "Name" %}</th>
                        <td>{{ object.name }}</td>
                    </tr>
                </table>
            </div>
            {% include 'inc/panels/custom_fields.html' %}
        </div>
    </div>
{% endblock %}

{% block modals %}
  {% include 'inc/htmx_modal.html' %}
{% endblock modals %}

netbox_mikrotik/templates/netbox_mikrotik/mikrotikdhcpserver_leases.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load i18n %}
{% load plugins %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <h5 class="card-header">
                {% trans "DHCP Leases" %}
                <div class="card-actions">
                    {% if perms.netbox_mikrotik.add_mikrotikdhcplease %}
                        <a href="{% url 'plugins:netbox_mikrotik:mikrotikdhcplease_add' %}?mikrotik_dhcp_server={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-ghost-primary btn-sm">
                          <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Create DHCP Lease" %}
                        </a>
                    {% endif %}
                </div>
            </h5>
            {% htmx_table "plugins:netbox_mikrotik:mikrotikdhcplease_list" id=object.pk %}
        </div>
    </div>
    <div class="col-md-6">
        <div class="card"></div>
    </div>
</div>

{% endblock %}

netbox_mikrotik/templates/netbox_mikrotik/object.html
{% extends 'generic/_base.html' %}
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load perms %}
{% load plugins %}
{% load tabs %}
{% load i18n %}

{% comment %}
Blocks:
  - page-header:          Content displayed above the primary page content
    - breadcrumbs:        Breadcrumb list items (HTML <li> elements)
    - object_identifier:  Unique identifier for the object
  - title:                Page title
  - subtitle:             Additional context displayed below the title
  - controls:             Control elements displayed between the header and content
    - control-buttons:    Action buttons (add/edit/delete/etc.)
      - extra_controls:   Any additional action buttons to display
  - tabs:                 Page tabs
  - content:              Primary page content
  - modals:               Any pre-loaded modals

Context:
  - object: The object being viewed
{% endcomment %}

{% block page-header %}
  <div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mt-2">

      {# Breadcrumbs #}
      <ol class="breadcrumb" aria-label="breadcrumbs">
        {% block breadcrumbs %}
          <li class="breadcrumb-item">
            <a href="{% url object|viewname:'list' %}">{{ object|meta:'verbose_name_plural'|bettertitle }}</a>
          </li>
        {% endblock breadcrumbs %}
      </ol>

      {# Object identifier #}
      <code class="d-block text-muted bg-transparent px-0">
        {% block object_identifier %}
          {{ object|meta:"app_label" }}.{{ object|meta:"model_name" }}:{{ object.pk }}
          {% if object.slug %}({{ object.slug }}){% endif %}
        {% endblock object_identifier %}
      </code>

    </div>
  </div>
  {{ block.super }}
{% endblock page-header %}

{% block title %}{{ object }}{% endblock %}

{% block subtitle %}
  <div class="text-secondary fs-5">
    {% trans "Created" %} {{ object.created|isodatetime:"minutes" }}
    {% if object.last_updated %}
      <span class="separator">&middot;</span>
      {% trans "Updated" %} {{ object.last_updated|isodatetime:"minutes" }}
    {% endif %}
  </div>
{% endblock subtitle %}

{% block controls %}
  <div class="btn-list justify-content-end mb-2">
    {% plugin_buttons object %}

    {# Add/edit/delete/etc. buttons #}
    {% block control-buttons %}

      {# Extra buttons #}
      {% block extra_controls %}{% endblock %}

      {# Default buttons #}
      {% if perms.extras.add_bookmark and object.bookmarks %}
        {% bookmark_button object %}
      {% endif %}
      {% if perms.extras.add_subscription and object.subscriptions %}
        {% subscribe_button object %}
      {% endif %}
      {% if request.user|can_add:object %}
        {% clone_button object %}
      {% endif %}
      {% if request.user|can_change:object %}
        {% edit_button object %}
      {% endif %}
      {% if request.user|can_delete:object %}
        {% delete_button object %}
      {% endif %}
    {% endblock control-buttons %}
  </div>

  {# Custom links #}
  <div class="d-flex justify-content-end">
    <div class="btn-list">
      {% block custom-links %}
        {% custom_links object %}
      {% endblock custom-links %}
    </div>
  </div>
{% endblock controls %}

{% block tabs %}
  <ul class="nav nav-tabs" role="presentation">
    {# Primary tab #}
    <li class="nav-item">
      <a class="nav-link{% if not tab %} active{% endif %}" href="{{ object.get_absolute_url }}">{{ object|meta:"verbose_name"|bettertitle }}</a>
    </li>

    {# Include tabs for registered model views #}
    {% model_view_tabs object %}
  </ul>
{% endblock tabs %}

{% block alerts %}
  {% plugin_alerts object %}
{% endblock alerts %}

{% block content %}{% endblock %}

{% block modals %}
  {% include 'inc/htmx_modal.html' %}
{% endblock modals %}