netbox_mikrotik/urls.py
from django.urls import include, path
from utilities.urls import get_model_urls

from netbox_mikrotik.views import *  # noqa: F401

app_name = "netbox_mikrotik"

urlpatterns = [path("dhcp-servers/",
                    include(get_model_urls(app_name, "mikrotikdhcpserver", detail=False))),
               path("dhcp-servers/<int:pk>/",
                    include(get_model_urls(app_name, "mikrotikdhcpserver"))),
               path("dhcp-leases/",
                    include(get_model_urls(app_name, "mikrotikdhcplease", detail=False))),
               path("dhcp-leases/<int:pk>/",
                    include(get_model_urls(app_name, "mikrotikdhcplease"))),
               path("devices/",
                    include(get_model_urls(app_name, "mikrotikdevice", detail=False))),
               path("devices/<int:pk>/",
                    include(get_model_urls(app_name, "mikrotikdevice")))]

netbox_mikrotik/models/device.py
from django.db.models import CharField, OneToOneField, BooleanField, DateTimeField, CASCADE
from django.utils.translation import gettext_lazy as _
from tenancy.models import Tenant
from ipam.models import IPAddress
from netbox.models import NetBoxModel

__all__ = ("MikrotikDevice",)


class MikrotikDevice(NetBoxModel):
    device = OneToOneField(
        verbose_name=_("Device"),
        to="dcim.Device",
        on_delete=CASCADE,
        related_name="mikrotik_device",
        null=False,
        blank=False
    )
    username = CharField(max_length=64, null=False, blank=False)
    password = CharField(max_length=254, null=False, blank=False)
    address_list_sync = BooleanField(default=False)
    dns_sync = BooleanField(default=False)
    dhcp_sync = BooleanField(default=False)
    last_run = DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "netbox_mikrotik_device"
        verbose_name = _("Device")
        verbose_name_plural = _("Devices")
        ordering = ["device__name"]

    def __str__(self):
        return self.device.name

    @property
    def name(self) -> str:
        return str(self)

    @property
    def tenant(self) -> Tenant | None:
        return self.device.tenant

    @property
    def ip_address(self) -> IPAddress | None:
        if self.device.primary_ip4:
            return self.device.primary_ip4
        if self.device.primary_ip6:
            return self.device.primary_ip6
        for interface in self.device.interfaces.all():
            for ip in interface.ip_addresses.all():
                return ip
        return None

netbox_mikrotik/forms/device.py
from django.forms import PasswordInput
from netbox.forms import NetBoxModelForm

from netbox_mikrotik.models import MikrotikDevice

__all__ = ("MikrotikDeviceForm",)


class MikrotikDeviceForm(NetBoxModelForm):
    class Meta:
        model = MikrotikDevice
        fields = [
            "device",
            "username",
            "password",
            "address_list_sync",
            "dns_sync",
            "dhcp_sync"
        ]
        widgets = {
            "password": PasswordInput(render_value=True),
        }

netbox_mikrotik/api/views/device.py
from netbox.api.viewsets import NetBoxModelViewSet

from netbox_mikrotik.models import MikrotikDevice
from netbox_mikrotik.api.serializers import MikrotikDeviceSerializer

__all__ = ("MikrotikDeviceViewSet",)


class MikrotikDeviceViewSet(NetBoxModelViewSet):
    queryset = MikrotikDevice.objects.all()
    serializer_class = MikrotikDeviceSerializer
    # filterset_class = filtersets.FloorplanFilterSet # ToDo

netbox_mikrotik/views/device.py
from netbox.views.generic import ObjectListView, ObjectView, ObjectEditView, ObjectDeleteView, BulkImportView, \
    BulkEditView, BulkDeleteView
from utilities.views import register_model_view

from netbox_mikrotik.models import MikrotikDevice
from netbox_mikrotik.tables import MikrotikDeviceTable
from netbox_mikrotik.filtersets import MikrotikDeviceFilterSet
from netbox_mikrotik.forms import MikrotikDeviceForm

__all__ = ("MikrotikDeviceListView",
           "MikrotikDeviceView",
           "MikrotikDeviceEditView",
           "MikrotikDeviceDeleteView",
           "MikrotikDeviceBulkImportView",
           "MikrotikDeviceBulkEditView",
           "MikrotikDeviceBulkDeleteView")


@register_model_view(MikrotikDevice, "list", path="", detail=False)
class MikrotikDeviceListView(ObjectListView):
    queryset = MikrotikDevice.objects.all()
    filterset = MikrotikDeviceFilterSet
    # filterset_form = MikrotikDeviceForm ' ToDo
    table = MikrotikDeviceTable


@register_model_view(MikrotikDevice)
class MikrotikDeviceView(ObjectView):
    queryset = MikrotikDevice.objects.all()


@register_model_view(MikrotikDevice, "add", detail=False)
@register_model_view(MikrotikDevice, "edit")
class MikrotikDeviceEditView(ObjectEditView):
    queryset = MikrotikDevice.objects.all()
    form = MikrotikDeviceForm


@register_model_view(MikrotikDevice, "delete")
class MikrotikDeviceDeleteView(ObjectDeleteView):
    queryset = MikrotikDevice.objects.all()


@register_model_view(MikrotikDevice, "bulk_import", detail=False)
class MikrotikDeviceBulkImportView(BulkImportView):
    queryset = MikrotikDevice.objects.all()
    # model_form = ViewImportForm # ToDo
    table = MikrotikDeviceTable


@register_model_view(MikrotikDevice, "bulk_edit", path="edit", detail=False)
class MikrotikDeviceBulkEditView(BulkEditView):
    queryset = MikrotikDevice.objects.all()
    # filterset = ViewFilterSet # ToDo
    table = MikrotikDeviceTable
    # form = ViewBulkEditForm # ToDo


@register_model_view(MikrotikDevice, "bulk_delete", path="delete", detail=False)
class MikrotikDeviceBulkDeleteView(BulkDeleteView):
    queryset = MikrotikDevice.objects.all()
    # filterset = ViewFilterSet # ToDo
    table = MikrotikDeviceTable

netbox_mikrotik/templates/netbox_mikrotik/device/mikrotik.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load i18n %}
{% load plugins %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <h5 class="card-header">
                {% trans "Security Zones" %}
                <div class="card-actions">
                    {% if perms.netbox_mikrotik.add_mikrotikdevice %}
                        <a href="{% url 'plugins:netbox_mikrotik:mikrotikdevice_add' %}?return_url={{ object.get_absolute_url }}" class="btn btn-ghost-primary btn-sm">
                          <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Create Security Zone" %}
                        </a>
                    {% endif %}
                    {% if perms.netbox_mikrotik.add_mikrotikdevice %}
                        <a href="{% url 'plugins:netbox_mikrotik:mikrotikdevice_add' %}?assigned_object_type={{ object|content_type_id }}&assigned_object_id={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-ghost-primary btn-sm">
                          <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Assign Security Zone" %}
                        </a>
                    {% endif %}
                </div>
            </h5>
            {% htmx_table 'plugins:netbox_mikrotik:mikrotikdevice_list' device_id=object.pk %}
        </div>
    </div>
    <div class="col-md-6">
        <div class="card"></div>
    </div>
</div>

{% endblock %}